version: '3'
services:
  task-api:
    image: microservicesdemolyon/task-api-dev
    container_name: task-api
    build: 
      context: ./service-task-api
      dockerfile: Dockerfile-dev
    volumes:
        - ./service-task-api:/src
    environment:
      - DB_URL=mongodb://mongo/tasks
    ports: 
      - "4200:4200"
  frontend:
    image: microservicesdemolyon/frontend-dev
    container_name: frontend
    build: 
      context: ./service-frontend
      dockerfile: Dockerfile-dev
    volumes:
        - ./service-frontend:/src
    ports: 
      - "4300:4300"
  mongo:
    image: microservicesdemolyon/mongo
    container_name: mongo
    build: ./service-mongo
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: