version: '3'
services:
  task-api:
    image: microservicesdemolyon/task-api
    build: ./service-task-api
    environment:
      - DB_URL=mongodb://mongo/tasks
      - ENABLE_CORS=true
    ports: 
      - "4200:4200"
  frontend:
    image: microservicesdemolyon/frontend
    build: ./service-frontend
    ports: 
      - "4300:4300"
  mongo:
    image: microservicesdemolyon/mongo
    build: ./service-mongo
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: