version: '3'
services:
  api:
    image: microservicesdemolyon/task-api
    build: ./service-task-api
    ports: 
      - "4200:4200"
  mongo:
    image: microservicesdemolyon/mongo
    build: ./service-mongo
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: